### PR TITLE
Fix for crashes in PHP8

### PR DESCRIPTION
**Pull request by johanwilfer**

### CODE REVIEW

**Comment by johanwilfer** [comment]
The @each is removed in php 8, to fix crashes I replaced with foreach.

**Comment by johanwilfer** [comment]
@bihla Could you have a look here and maybe merge this? We run this version in production and would like to be able to your your upstream again instead of our fork

**Comment by johanwilfer** [comment]
Ping here? Can we get this merged please?

**Review by bihla — APPROVED** [review]
Hej. Tackar!

**Comment by johanwilfer** [comment]
@bihla Thanks for the accept, can this be merged then please? So we can switch back to your repro?

**Comment by johanwilfer** [comment]
Seems like this is addressed in the latest version, will close this PR then.

**Pull request closed without merging**
